site_name: Документация API
site_author: (C) 2024, BASIS
site_description: Содержание
site_url: https://basis.api.doc.ru/

#repo_name: Rostelecom-IT/help-camera-rt
#repo_url: https://gitlab.com/Rostelecom-IT/help-camera-rt

theme:
  name: material
  custom_dir: overrides
#  static_templates:
#    - sitemap.html
  language: ru
  logo: ./basis_full-logo_white.png
  favicon: ./basis_short-logo_color.png
  palette:
    scheme: default
    primary: rt-white
    accent: rt-orange
  features:
    - navigation.tabs
    - search.highlight
    - toc.integrate
    - navigation.top
    - content.tooltips

#extra_css:
#- ./assets/stylesheets/extra.css

nav:
#  - Главная страница: index.md
  - Обзор: review.md
  - Аутентификация и авторизация: authentication_and_authorization.md
  - Руководство по началу работы: getting_started_guide.md
  - Справочник API:
    - Swagger: api_reference_sw.md
    - ReDoc: api_reference_rd.md
  - Примеры использования API: api_usage_examples.md
  - История изменений: history_of_changes.md
  - Контакты: contacts.md
  - Глоссарий: glossary.md

extra_javascript:
  - https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js
  - https://unpkg.com/swagger-ui-dist/swagger-ui-standalone-preset.js
extra_css:
  - https://unpkg.com/swagger-ui-dist/swagger-ui.css
