Обзор
Аутентификация и авторизация

== Начало работы с «Базис.Virtual Protect» API

Доступ к Swagger Базис.Virtual Protect осуществляется из стартовой страницы в верхнем правом углу.

Рисунок 1

После этого откроется интерактивное меню со списком функций.

Рисунок 2

API разделено на сервисы, которые можно изменить в верхнем правом углу.

Рисунок 3

Если в списке для «Archive Manager API» нажать на «POST /v1/archives/internal/flb», откроется форма, которая позволяет создавать бэкап выбранной директории.

Рисунок 4

Нажмите кнопку «Try it out» для разблокирования операции ввода значений. Введите обязательные параметры (* required) и те, которые посчитаете необходимыми

Рисунок 5

Нажмите «Execute». Результат выполнения, тип результата, код ответа сервера и строка с URL-запросом отобразятся в блоке «Responses» под данной кнопкой.

Рисунок 6

== Описание API
URL: <«Базис.Virtual Protect» controller URL>/<URL функции>

Например, для функции List flb archives (Получение списка архивов, созданных файловыми агентами) полный URL-адрес запроса: <«Базис.Virtual Protect» controller URL>/v1/archives/flb/